version: '3'
services:
  php_fpm_laravel_admin:
    build: ./code
    container_name: php_fpm_laravel_admin
    image: php:7.4-fpm
    volumes:
      - ./code:/var/www/html/
    networks:
      - la-network
    depends_on:
      - mysql_laravel_admin
  nginx_laravel_admin:
    container_name: nginx_laravel_admin
    image: nginx
    volumes:
      - ./code:/var/www/html/
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    links:
      - php_fpm_laravel_admin
    networks:
      - la-network
  mysql_laravel_admin:
    container_name: mysql_laravel_admin
    hostname: mysql-container
    image: mysql:5.7
    platform: linux/amd64 # 給M1晶片使用
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
      - ./conf/mysql:/etc/mysql/conf.d
    networks:
      - la-network

networks:
  la-network:
    driver: bridge
